### PR TITLE
Fedora and CentOS spec file to build rpm packages

### PR DESCRIPTION
**Pull request by rferris**
working specfile to make building rpm packages easier.

### CODE REVIEW

**Comment by XinyuHou** [comment]
@rferris 
Thank you for the pull request.

Is there an issue associated to this pull request?

**Comment by rferris** [comment]
@XinyuHou Not to my knowledge, no.

**Comment by XinyuHou** [comment]
@rferris 
Could you raise an issue? Please put what the problem is and what the solution is.

**Comment by XinyuHou** [comment]
@nlyan @rferris 
Is this just for building source on rpm based system?

**Comment by nlyan** [comment]
Thanks for this @rferris. I'm sure it'll be useful. Packaging is going to be completely rewritten for v1.9 (and v2.0)

**Comment by nbolton** [comment]
This may not apply anymore, as the packaging scripts have been rewritten. Let me know if this needs reopening.

**Pull request closed without merging**
