### PR TITLE
Solve SonarCloud security hotspots and bugs

### PR DESCRIPTION
**Pull request by nbolton**
https://symless.atlassian.net/browse/S1-1717

To test:
1. Use GUI to connect 3 computers (Windows, macOS, and Linux)
2. Test server and client mode on every OS (i.e. 6 combinations)

### CODE REVIEW

**Review by aquacash5 — CHANGES_REQUESTED** [review]
Linux and Windows work fine, but macOS refused to start.

https://app.screencast.com/MqyFlmktML8F3

**Comment by nbolton** [comment]
> macOS refused to start.
> 
> https://app.screencast.com/MqyFlmktML8F3

Oh dear. I'm sure that was working for me but I'll try to reproduce.

**Comment by nbolton** [comment]
> macOS

@aquacash5 What version of macOS?

**Comment by aquacash5** [comment]
> What version of macOS?

Sonoma 14.5

**Comment by nbolton** [comment]
> > What version of macOS?
> 
> Sonoma 14.5

I installed a fresh macOS 14 VM (Virtual Buddy) and it works. Is yours a fresh install through Virtual Buddy?

**Review by aquacash5 — APPROVED** [review]

**Pull request merged**
