### PR TITLE
Modern icons for application and menu bar on Mac

### PR DESCRIPTION
**Pull request by statico**
Inspired by @amandamcg's awesome icons in https://github.com/symless/synergy/issues/4825 and the open issue https://github.com/synergy/synergy/issues/4736, I've updated the application icon to match the modern logo an flat sensibilities as well as the menu bar icons on OSX:

image

OSX light theme:
screen shot 2015-08-08 at 6 21 46 pm

OSX dark theme:
screen shot 2015-08-08 at 6 23 12 pm

The icons look a little bold right now because retina-quality icons aren't drawn properly by Qt 4.x, which is the version used by Synergy. [The problem appears to be fixed in Qt 5.x](https://bugreports.qt.io/browse/QTBUG-33441) so retina menu icons should display properly if Synergy upgrades. Here's a mockup:

screen shot 2015-08-08 at 6 21 46 pm
screen shot 2015-08-08 at 6 23 12 pm

If nobody likes this, that's totally fine. Feel free to use the source files for any purpose:
- https://statico-misc.s3.amazonaws.com/synergy-icons-2015/synergy-icon-2015.ai
- https://statico-misc.s3.amazonaws.com/synergy-icons-2015/synergy-icon-2015.psb

Also, the addition of Objective-C++ to the `src/gui/` subproject seems a little unorthodox but I couldn't find a clean way to have the code live in `src/lib/platform`.

### CODE REVIEW

**Comment by amandamcg** [comment]
This is awesome!

**Comment by XinyuHou** [comment]
Please test the nightly.
http://synergy-project.org/nightly?filter=synergy-pr4937-modern-icons-on-mac-beta-0823877

This is not a guaranty that this PR will be merged.

**Comment by statico** [comment]
Works fine for me.

**Comment by youngpilot** [comment]
Can't find the nightly anymore. Will it be merged to the master anytime soon?

**Comment by XinyuHou** [comment]
@youngpilot @statico 
Could you guys test this nightly?
http://symless.com/nightly?filter=83320f2

**Comment by youngpilot** [comment]
Hey, thanks for caring about the retina menu issue :)

Unfortunately now the whole program is not-retina as well as the menu bar icon.
Screenshot: https://www.dropbox.com/s/rssugi57ujleex3/Screenshot%202016-12-07%2020.19.49.png?dl=0

All the best,
Julian Schiemann
https://about.me/julian.schiemann

**Comment by statico** [comment]
Confirmed, same as @youngpilot

**Comment by XinyuHou** [comment]
@statico @youngpilot 
Do we need to upgrade our build machine to use Qt 5.x to get retina quality?

**Comment by statico** [comment]
@XinyuHou Yes, I think the project needs to be upgraded to Qt 5, which has high-DPI capability. At least, I think so — it's been a while since I made this PR :)

**Comment by XinyuHou** [comment]
@statico 
Thanks, our new build machine just arrived. It's a good time we upgrade the whole build system. Please sit tight. After we have the first nightly built from our new buildbot. I will post them in there.

**Comment by RubyGemer** [comment]
nightly page is not available?

**Comment by IncognitoCore** [comment]
Can we expect this feature to be implemented in the next release?

**Comment by nlyan** [comment]
@IncognitoCore all cosmetic changes have been pushed back to v2.0, which is due to go to in to beta inside the next month or two.

**Comment by IncognitoCore** [comment]
@nlyan Thanks for the fast reply! Looking forward to version 2:)

**Comment by vayan** [comment]
Since 2.0 is back to beta could we please get this to be merged?

**Comment by nbolton** [comment]
Let me know if this is still valid, and I'll reopen.

**Comment by sebbean** [comment]
@nbolton yep definitely still valid

**Comment by Jnewbon** [comment]
Getting an error after conflict resolution

```
[ 92%] Linking CXX executable ../../bin/synergy
Undefined symbols for architecture x86_64:
  "isOSXInterfaceStyleDark()", referenced from:
      MainWindow::setIcon(MainWindow::qSynergyState) in MainWindow.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/synergy] Error 1
```

As merging wasn't simple this won't make it into the v1.11.0 release

**Comment by sebbean** [comment]
pinging @statico 

if you have a few min to conflict resolve (guessin you're the best guy to do it?)

we can get this on the mainline!

**Comment by statico** [comment]
I would definitely like to help, but I don’t have the time to get to this
in the next few months. Sorry!

**Comment by Jnewbon** [comment]
So after looking in this, solving the conflicts, it seems the .mm file created wasn't being included in the cmake build list, so adding a Darwin check and adding it the build worked. 

I currently don't have a mac to test on, but the CI test shows the build works. ill be able to test if the new icons are used when i get back into the office. 

The branch with the changes are is [statico-statico-icons](https://github.com/symless/synergy-core/tree/statico-statico-icons) (Interesting name that was auto generated by git)

**Pull request merged**
