### PR TITLE
Replace deprecated mouse_event with SendInput

### PR DESCRIPTION
**Pull request by axela74**
Many games don't work well when we send the mouse wheel input using mouse_event, using SendInput make them respond correctly to this kind of event. Btw I think that we should remove all mouse_event and keybd_event call and use only SendInput as mouse_event and keybd_event are deprecated.

### CODE REVIEW

**Comment by axela74** [comment]
speaker: no reason, only me beeing lazy! :-)

**Comment by nbolton** [comment]
Possibly related to #4349? @speaker

**Comment by raphendyr** [comment]
Just as a git note from synergy user... Probably you could merge at least few of those commits and also you could remove those old code lines (currently commented).

**Comment by axela74** [comment]
raphendyr: I'm a git newbie, how I merge the commits?

**Comment by axela74** [comment]
@nbolton I'm using the synergy windows client with these changes and the bug @4349 is still present :-( My changes however resolved many problems with the mouse wheel in many games.

**Comment by raphendyr** [comment]
Well. Not sure what tool you are using, but you can edit your git history. E.g. ion eclipse egit, you can select history item and choose to squash it.
Here is your commits rebased and I removed the comments, so now you can better see what was removed and what was added. https://github.com/raphendyr/synergy/commits/rebased_axela74_patch1

**Comment by raphendyr** [comment]
And direct link to compare view https://github.com/synergy/synergy/compare/master...raphendyr:rebased_axela74_patch1
Shows nicely all the difference that this commit does.

ps. those `0` -> `MOUSE_something` changes are not done.

**Comment by nbolton** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) this PR, which usually takes about 30 minutes. When done, it'll upload the packages to our [nightly builds page](http://synergy-project.org/nightly?filter=pr-axela74-mouse_event-fix). Happy testing!

**Comment by XinyuHou** [comment]
@axela74 
Please remove those unused code.

**Pull request closed without merging**
