### PR TITLE
Build tests again

### LINKED ISSUE #6620: v1.11.0 no longer builds tests
After this [commit](https://github.com/symless/synergy-core/commit/688095d0a7d22704b5c3282bc68b41ceca42ab7e) was added to the master branch, building synergy no longer builds the tests.

Is this an intentional change? If so, how do I build the tests?

### PR DESCRIPTION
**Pull request by talyz**
Fixes #6620 
The tests were accidentally disabled in 688095d0a7d22704b5c3282bc68b41ceca42ab7e. Since then, the code has drifted slightly: the synergy lib has been renamed from synergy to synlib in 4263fd17177d7717b04ac6d6ec62efa2f657ed74 and the curl dependency was dropped in 491bb2de000245a943b8298462c4a9d8f34c9a44.

This re-enables the tests, targets the right lib and removes the obsolete test.

### CODE REVIEW

**Comment by talyz** [comment]
I did this as a part of https://github.com/NixOS/nixpkgs/pull/80138 (upgrading synergy in nixpkgs, the `NixOS` package repository), where we also have to update `gtest` and `gmock` to the latest version to successfully build and run the tests. I don't know how you want to handle that going forward - if you just want to update the vendored lib, import it as a submodule or something else.

**Comment by talyz** [comment]
@Jnewbon Is this supposed to target `v1-dev` instead?

**Comment by Jnewbon** [comment]
No, I'm closing out v1-dev permanently after v1.11.1 is delivered.

Keeping a development branch, in theory, is good, as it separates the development from known working code. but it creates some overhead that can get messy, in the sense that as v1-dev is merged into master the merge commits don't exist on v1-dev and it gets confusing seeing that v1-dev is x commits behind the master.

Also, no one opens a pull request to v1-dev as its not the default branch. So we are changing it so master will be the latest and greatest, and stable release will be tagged and released the Releases section.

**Comment by talyz** [comment]
@Jnewbon Aha, good to know. I'll keep this targeted to `master`, then.

Yep, doing it the other way round, doing development on `master` and branching for releases can be less confusing and works pretty well, but tagging releases should be enough for synergy :+1:

Have you had any time to look at the PR? 🙂

**Comment by Jnewbon** [comment]
I have seen it, but not had any time to really review it. The tests where disabled quite some time ago, so i want to make sure i have the time to really get into it. 

They must of been disabled for a reason and I haven't looked into why.

**Comment by talyz** [comment]
Aha, I see.

Well, as I wrote in my first post they were removed in 688095d0a7d22704b5c3282bc68b41ceca42ab7e where the only comment given is `Remove IRIX nonsense` - nothing about disabling the tests, which would have been much more important to mention if done intentionally, so I'm guessing it was a mistake. The wiki also still says that the tests should be built with the product.

**Comment by Jnewbon** [comment]
Ah thanks for that, Looks like it was an accidental removal of the tests, so I don't see any reason not to add them back in.

**Comment by Jnewbon** [comment]
I'm going to hold off merging this PR for the moment till 1.11.1 is settled into the master branch as we are changing the way we deliver changes to make things easier.

**Comment by talyz** [comment]
Okay, great! Once 1.11.1 is merged, I can rebase on master and make sure everything still works as expected 🙂

**Comment by Jnewbon** [comment]
@talyz 1.11.1 has just been merged, if you want to do the rebase.

**Comment by talyz** [comment]
@Jnewbon Done! Builds and works fine in my tests.

**Comment by Jnewbon** [comment]
Awesome, Just need to fix the failing test and ill be able to add it to the CI builds for automated testing again.

**Pull request merged**
