### PR TITLE
Add clipboard read events timeout on Linux

### PR DESCRIPTION
**Pull request by nneul**

### CODE REVIEW

**Comment by nneul** [comment]
Resolves #6409

**Comment by nneul** [comment]
Or at least masks the hang by timing out. Probably some better fix that actually addresses what isn't working.

**Comment by Jnewbon** [comment]
Deleted and recreated v1-dev which autoclosed the PR.

**Comment by nneul** [comment]
@Jnewbon This is a trivial fix to a clearly defined problem, is there some reason it's still not merged?

**Comment by Jnewbon** [comment]
I have reproduced this bug and I can confirm that this PR fixes it. so I have merged it.

**Pull request merged**
