### PR TITLE
Fix broken hotkeys on macOS servers

### PR DESCRIPTION
**Pull request by spurin**
#3705
Can we have this in the next release please?

### CODE REVIEW

**Comment by nlyan** [comment]
Yes, we will likely merge this in to v1.8.7

**Comment by spurin** [comment]
See:

https://github.com/symless/synergy/issues/3705
https://github.com/symless/synergy/pull/5522

Can we get this in 1.8.8?  It's a bit of a joke how long this has gone on for in general, not to mention with a working fix and positive feedback ... there's also the fact that the people who pay for the product can't use the latest features and the only version we have with the patched fix (the 1.8.6 nightly build which I now am hosting for the many who have the same issue), keeps losing the pro functionality every time it upgrades.

Somewhat disgruntled....

**Comment by hovissimo** [comment]
@nbolton What a joke. One of your customers (someone who is PAYING YOU) has also written and validated code that fixes a long outstanding bug in your software, and you can't find the time to double check it and pull it in? @spurin has bent over backwards to support you, but apparently you can't find an hour here and there to take care of your customers.

Fucking shameful.

**Comment by spurin** [comment]
@hovissimo I'm not one for normally voicing my issues in the same way that you have but I am feeling that same annoyance that you mention.  There has been efforts put in to resolve this issue out of sheer frustration. 

I doubt this issue affects any of the Synergy staff team or is one that even crops up that often for the direction in which the companies more recent emails hint at and that is of the sales/marketing directed at the enterprise.  It is also somewhat ironic to receive a mail that is pretty much slamming the door on support even though you've apparently paid for that lifetime of 'Pro' support?  I'm not even asking for support on this, I've pretty much done most of the efforts with the fix, the feedback, the user testing, hosting a working version, not to mention support on the 3 discussion threads about this!  Why is this not on your radar.

If you're using synergy with multiple monitors then you're probably in the 'safe zone', however, if like myself who uses Synergy on a HDMI switch or like MANY of the others who've had this issue for other reasons, dating back to 2014, you're pretty much the unloved of the companies objectives in terms of a fix or priority.

There's obviously much more important things to address like making certain Japanese keys work (https://github.com/symless/synergy/pull/5730) ... an issue that affects 1 person, was raised in November 2016 and has been targeted for 1.8.8.  Excellent Triage system guys.   There's many other examples of a similar ilk

I've paid for SSL functionality and on 1.7.6 it's ropey as, actually that just being polite.  It's unusable for anything long term, yet I'm stuck on this because for whatever reason (please feel free to enlighten us as it seems like radio silence), the Synergy team wont even take the time to give us feedback other than the odd label of '1.9 Could' '1.10 Could', here's a label that's appropriate

'1.Next.Release.Because.We.Care.About.Our.Users...Honest'

@nbolton @nylan @XinyuHou ... wake up

**Comment by XinyuHou** [comment]
@spurin 
We really appreciate your effort.

Because of many reasons, we are not working on next stable release at the moment. But we consider to merge this PR in the next stable version.

Before we do that, we want to do a bit more investigation about the changed code. While we are reviewing the changes, we realize there are some legacy code we don't fully understand. Hopefully we could get it clear in next release.

Thanks

**Comment by jimsimonz** [comment]
Just FYI, Running the latest Sierra (10.12.5) with either the stable release or the build of this branch (pr5522), hotkeys are not working for me. MBP server + win 10 client.

**Comment by spurin** [comment]
@jimsimonz

I will help you resolve this if you're still having the issue.  There's lots of people who successfully have this working with this PR using same setup as you so I think it's a config issue (which can be difficult to troubleshoot owing to keyboard/setup variations).

Reach out to me direct if you want to investigate further 👍

**Comment by jimsimonz** [comment]
@spurin Thanks for getting back. Do you have a link to the pull request binaries? Since last testing it, I can't find a valid link to download and re-test it. 

I just tried the 1.9 rc and the PR's not gone into that. I'm considering building and debugging the whole thing myself at some point.

@nbolton @nylan @XinyuHou how hard is it to integrate a few lines of code dudes?

**Comment by spurin** [comment]
@jimsimonz

I removed the binaries.  I was hosting these myself and felt that this masking the problem somewhat as people would encounter the issue, download the patched binaries and correspondingly the problem would go on without being apparent (even though ... this thread and the others speak volumes...)

If you email me, my email is james @ my github id .com

I will mail you links for the binaries and we'll get this sorted for you. 

Again reiterating ... @nbolton @nylan @XinyuHou ... the code works, granted hotkeys are difficult to implement sometimes owing to variations in keyboards / kvm's ... but, it works.  There are reports in these threads covering every major version.

Can you please fix this.  If it's not going to be done, I will fork your repo, track changes upstream and provide a release on a corresponding URL: SynergyWithHotkeys.com 🤔

Not what I want to do really 😛

**Comment by WibbletheDuck** [comment]
```Be quick and get exclusive early access to Synergy 2 for only $15.```

Ah yes, act fast and for only $15 more I can get a bunch of 3+year-old bugs with a shiny new chrome-plated finish! 🎉 👌 😌 

screen shot 2017-10-12 at 1 13 29 pm

**Comment by spurin** [comment]
Is this resolved @Jnewbon?

**Comment by nbolton** [comment]
@spurin Hey there, thanks for your patience. This PR was auto-closed by GitHub. We will update this ticket when we have some news.

**Comment by Jnewbon** [comment]
Deleted and recreated v1-dev which autoclosed the PR.

**Comment by spurin** [comment]
Any plan to get this merged? It’s been a long time, I’m still using the old build with the fix

**Comment by Jnewbon** [comment]
The fix by the looks of it removes a check that may affect OS specific hotkeys. A lot of testing needs to be done before I can merge this. 

When I built this branch it fixes a couple of hotkeys but not all of them which leads me to believe the problem may actually exist elsewhere

**Comment by spurin** [comment]
Can you elaborate on what hotkeys did not work for you and the keys that OS Specific Hotkeys, in my testing it worked as expected although, that may be specific to the keys I used (function)

**Comment by Jnewbon** [comment]
@spurin Sorry for the delay getting back to you, I was pulled into getting urgent fixes/updates done on the website.

I just rebuilt this change rebased on v1-dev. I believe the problems I saw earlier are something to do with my modifier key setup. it seems the majority of the modifiers work with this fix and with the number of people confirming it works, I'm happy enough to merge it in.

**Pull request merged**
