### PR TITLE
Dependencies not found with the 'check_' macros

### PR DESCRIPTION
**Pull request by renegart**
I've a side-by-side installation in my home directory with several package needed as dependencies by Synergy. The dependencies are not found correctly with the 'check__' macros. So I've rewritten the search of the dependencies with use of *pkg_check_modules_.

It could be extended to search also for e.g. pthread, but I didn't want to change parts shared with other platforms without able to test it.

### CODE REVIEW

**Comment by speaker** [comment]
Thanks for the pull request! I created a branch for you (https://github.com/synergy/synergy/tree/pr-renegart-pkg-find-package-dependencies). Buildbot is now [building](http://buildbot.synergy-project.org/builders) (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr-renegart-pkg-find-package-dependencies). Happy testing!

**Comment by renegart** [comment]
Thx for the branch. I'm not sure how to proceed further. I'd a look into the build outputs. It seems there are several issues which prevents a successful build. I could try to fix them, but that's more or less issues from master branch and I'm not sure where to fix them...

**Comment by nbolton** [comment]
Hmm, didn't seem to upload any packages.

On Tuesday, April 21, 2015, Adam Potolsky <notifications@github.com> wrote:

> Thanks for the pull request! I created a branch for you (
> https://github.com/synergy/synergy/tree/pr-renegart-pkg-find-package-dependencies).
> Buildbot is now building <http://buildbot.synergy-project.org/builders>
> (it usually takes about 30 minutes). When done, the packages will be
> automatically uploaded (
> http://synergy-project.org/nightly?filter=pr-renegart-pkg-find-package-dependencies).
> Happy testing!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/synergy/synergy/pull/4542#issuecomment-94592324>.
>


-- 
--
Nick Bolton
Founder & CEO
<http://synergy-project.org/>
 +1 650-265-2044
 +44 (0)20 3598 3068

*Synergy:* Be more seamless

**Comment by renegart** [comment]
The build fails because of warnings and/or compile issues on the different platforms. So no build succeed.

**Comment by nbolton** [comment]
@speaker Please merge his changes into our pr branch.

**Comment by renegart** [comment]
I've updated the pull request. Now It should set all variables in 'config.h' correctly.

**Comment by XinyuHou** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) your pull request (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr4542). Please test and let me know if it worked.

**Comment by XinyuHou** [comment]
@renegart @moben 
Could you test this nightly?
http://synergy-project.org/nightly?filter=synergy-pr4542-dependencies-check-macro-beta-6e53abf

**Comment by nlyan** [comment]
I live this commit. Targetting for v1.9

**Comment by Jnewbon** [comment]
I'm going to close this PR, the base branch has been extensively changed since this was originally raised. 

If you still want this pulled in can you update the branch onto `v1-dev` and recreate the PR.

**Pull request closed without merging**
