### PR TITLE
Fixed missing include for Qt 5.11

### PR DESCRIPTION
**Pull request by darkdragon-001**
Qt 5.11 cleans up the internal headers and so consumers could fail by missing includes.

### CODE REVIEW

**Comment by Quintasan** [comment]
Can we get this merged? I'd like to be able to build Synergy on my machine.

**Comment by darkdragon-001** [comment]
This is a duplicate of #6359

**Comment by darkdragon-001** [comment]
This issue is a duplicate of #6359

**Comment by darkdragon-001** [comment]
Duplicate of #6359

**Comment by Jnewbon** [comment]
Duplicate of #6359

**Pull request closed without merging**
