### PR TITLE
#4036 Fix for client resolution change on Linux

### PR DESCRIPTION
**Pull request by trevormerritt**

### CODE REVIEW

**Comment by trevormerritt** [comment]
I want this fix.

**Comment by Jnewbon** [comment]
Sorry for the delay in getting round to this PR

Are you able to add a quick description on what this PR does to fix the linked issue?

**Comment by trevormerritt** [comment]
I have a laptop I put on a dock when I get to work.  That dock has a display attached giving me 2 displays to work from.  when my laptop becomes a client for the desktop PC, the Desktop PC acting as server is only aware of the original display size, not the new, larger area, constraining the pointer on the client PC (my laptop) to a corner in the upper left corner of the larger, external display on the left.

This patch checks if xinerama is enabled.
Then checks if there is >1 screen, and gets the sizes.
Then adds a listener for 'xconfigure.window == m_root' event.  
The listener sets the 'display size' to the new size, if there is one.

The patch allows me to put my laptop on the dock and synergy correctly updates the screen size.  The bug is 6 years old and I've been applying it manually and can't find the original source.  :(

I did not create this.  I found this patch and have been using it personally.  Hope it helps someone else.  :)

**Comment by trevormerritt** [comment]
Its doing the same kind of thing as  MSWindowsDesks::setShape(SInt32 x, SInt32 y,
                 SInt32 width, SInt32 height,
                 SInt32 xCenter, SInt32 yCenter, bool isMultimon)

**Comment by trevormerritt** [comment]
Bug is #4036

**Comment by trevormerritt** [comment]
Appears to be the same as PR 6439 from https://github.com/martinvanzijl

**Comment by Jnewbon** [comment]
Right, I see. I did see the other PR after I made the comment on this one but got pulled off onto other tasks again.

The PR is currently heading to the v2-dev branch which is now stale. If i switch this PR it will pull in a lot of change we don't want on the master branch, i see the original source repo has been deleted. So ill try do some git magic to cherry pick it onto a new branch.

**Comment by Jnewbon** [comment]
Closed as v2-dev is stale, opened new PR against master #6717

**Pull request closed without merging**
