### PR TITLE
IPv6 support for Windows and Linux

### PR DESCRIPTION
**Pull request by WilliamKyle**
Sorry for my bad operation here:
https://github.com/synergy/synergy/pull/4154

Tested in Windows 7 and debian 7. I don't have a MAC OS, so it is not tested.

PS: 
synergys run as ipv4 mode as default, use -a [::] to turn ipv6 mode.
I don't know how to modify synergy(GUI), so it is now only working start from terminal with args.

### CODE REVIEW

**Comment by nbolton** [comment]
@jakepetroules I tried finding your PR for IPv6, but there doesn't seem to be one. Was it a patch that never got applied?

**Comment by jakepetroules** [comment]
@nbolton I don't recall submitting a pull request for any IPv6-related functionality (nor do I usually work on networking-related functionality) - did you mean to ping someone else?

**Comment by nbolton** [comment]
@jakepetroules Sorry, I must be going mad, I thought you wrote an IPv6 patch, never mind!

**Comment by drzraf** [comment]
what's left to be done before synergy supports ipv6?

**Comment by legonigel** [comment]
Any chance this will ever get merged?

**Comment by XinyuHou** [comment]
This PR should solve https://github.com/symless/synergy/issues/4325

**Comment by XinyuHou** [comment]
@WilliamKyle 
Thank you for the pull request.

Would you mind fix the conflict? Then I will create a branch again.

**Comment by shaungc** [comment]
are we still waiting on a merge here?  Additionally, will the patch be expanded to include OS X at any point?

**Comment by killerfurbel** [comment]
First of all: I'm a noob in git and c++
But: I took the commit from WilliamKyle and applied it to the v1.9.0 Branch. I resolved the conflicts, didn't bother about the lib/plugin (since it is not available anymore), but applied the same logic also to lib/net/SecureListenSocket and did another change to IpcServer (third argument was missing for instantiation of new TCPListenSocket). Now it's building without any issues and by executing synergys -a [::] the server will listen on ipv6 - and client can connect to it, too.
It's working for me now (which is great), but I cannot resolve the conflicts here (no access). I attached the two commits/patches here so anybody can try it and then maybe resolve the conflicts.

(I'm not sure whether I should have done this against the master branch. I took 1.9.0 because it was compatible with VS 2015 and WilliamKyle's repo wasn't.)

[synergy-ipv6-patch.zip](https://github.com/symless/synergy/files/560089/synergy-ipv6-patch.zip)

**Comment by worthwhileindustries** [comment]
Any progress on this merge?

**Comment by wltjr** [comment]
Not sure about those conflicts but I am using these patches with 1.8.8 and its working fine, patches apply and work. I switched over to IPv6 :)

**Comment by wltjr** [comment]
I updated these patches in PR 6178. They should apply to master branch.

**Comment by wltjr** [comment]
@shaungc regarding OS X support. It may work on OS X just needs to be tested. There does not seem to be OS X specific code in the networking aspects of synergy. I assume OS X would have the same as BSD, which seems to be the same for most all *nix.

Has anyone tried the old or new patches on OS X? That maybe all that is required not sure.

**Comment by nbolton** [comment]
Fixed by #4154

**Pull request closed without merging**
