### PR TITLE
Mac SDK option broken in build script

### PR DESCRIPTION
**Pull request by rishubil**

### CODE REVIEW

**Comment by dendrochronology** [comment]
Can someone with write access take a look at these conflicts, please? Looks like issue #3797 is still hanging out there.

**Comment by jrolfs** [comment]
Are the conflicts the only things preventing this from getting merged? It would be great to get Synergy back into homebrew (I've paid for Synergy I just greatly prefer command line installation).

https://github.com/Homebrew/homebrew/pull/38200#issuecomment-112518038

**Comment by glyph** [comment]
Just echoing @jrolfs' sentiments here; it's not even "command line" installation that I prefer, it's just that homebrew already has one overarching update mechanism and the fewer of those I need to interact with the better :).

**Comment by benmccann** [comment]
@rishubil can you rebase?

@XinyuHou I'm not sure your suggestion that a space is missing is correct. From [the manual](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html):

    -sdk [sdkfullpath | sdkname]

So I don't think you should have a space in the middle of the string. And here's what we have [elsewhere in the file](https://github.com/symless/synergy/blob/master/ext/toolchain/commands1.py):

    shortForm = "macosx" + self.macSdk

So again, this reinforces `"macosx" + self.macSdk` being the valid form.

Perhaps this is a problem with the buildbot? How is that environment setup? Does it have xcode installed?

**Comment by XinyuHou** [comment]
@rishubil 
Would you mind fix the conflict? Then I will create a branch again.

**Comment by XinyuHou** [comment]
@benmccann 

>I also tried the command, "xcodebuild -version -sdk macosx 10.9 Path ", you used in the script on my Mac 10.9. It returns MacOSX10.10.sdk. I do have both versions of sdk in the SDKs folder.

I manually type in that command, our build machine have xcode installed. Right now we use a 10.11 OSX to build all Mac installers, from 10.6 to 10.11. We put all the SDK in one folder. Is it something wrong with the command I used? Why does  "xcodebuild -version -sdk macosx 10.9 Path" return 10.10 sdk?

**Comment by benmccann** [comment]
Can you type `xcodebuild -version -sdk macosx10.9` instead without the space?

**Comment by barthel** [comment]
@benmccann @XinyuHou Please push that issue forward to bring synergy to homebrew.

**Comment by nlyan** [comment]
This PR will be closed soon.

All bugs and PRs only relevant to the old build scripts will be closed upon release of v1.9.0-beta, which will not be using them, and will ship with new build instructions.

If there's anything in here build-system agnostic that needs fixing, please shout loudly now.

**Comment by XinyuHou** [comment]
Close as we are not using build script anymore.

**Pull request closed without merging**
