### PR TITLE
Remember skip-gui and skip-core options in config

### PR DESCRIPTION
**Pull request by neilmayhew**
This enables them to be used when building without having to specify
them again as options to the build step

[Review on Reviewable](https://reviewable.io/reviews/symless/synergy/4267)

### CODE REVIEW

**Comment by neilmayhew** [comment]
Any chance of having this merged?

**Comment by XinyuHou** [comment]
@neilmayhew 
Thank you for the pull request.

Is there an issue associated to this pull request?

**Comment by neilmayhew** [comment]
@XinyuHou No, sorry. This was something I encountered and fixed while building the software for myself. I didn't think to create an issue, especially since it's not a user-facing problem, just a developer one.

**Comment by nlyan** [comment]
This PR will be closed soon.

All bugs and PRs only relevant to the old build scripts will be closed upon release of v1.9.0-beta, which will not be using them, and will ship with new build instructions.

If there's anything in here build-system agnostic that needs fixing, please shout loudly now.

**Comment by XinyuHou** [comment]
Close as we are not using build script.

**Pull request closed without merging**
