### PR TITLE
Core builds

### LINKED ISSUE #6913: Add core assets to releases
Add binary assets to the releases. Specifically `synergys` and `synergyc`.

### PR DESCRIPTION
**Pull request by aquacash5**
Fixes #6913

# Additions
- Build scripts for `synergys` and `synergyc`
- Releases will have `synergys` and `synergyc` attached for each platform
- `SYNERGY_NO_LEGACY` environment variable turns off GUI and installers
- 

# Changes
- Change GitHub token to one that will propagate to other actions
- `job-build-*` -> `job-test-*`
- OpenSSL uses `find_package` instead of variables

# Removals
- Removed the OpenSSL library from the repository (Install the version from [https://slproweb.com/products/Win32OpenSSL.html](https://slproweb.com/products/Win32OpenSSL.html) or install with Chocolatey `choco install openssl`)

### CODE REVIEW

**Comment by ignacionr** [comment]
@aquacash5 please take a look at the failing builds; I think they may be able to be fixed by previously installing OpenSSL

**Review by ignacionr — CHANGES_REQUESTED** [review]
Please fix the failing builds by installing the required software before entering cmake.

**Comment by aquacash5** [comment]
> Please fix the failing builds by installing the required software before entering cmake.

On [`windows-2019`](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#tools) and [`macos-10.15`](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#utilities) OpenSSL is already installed on the runners. The various Linux containers: `symless/synergy-core:ubuntu20.04`, `symless/synergy-core:ubuntu19.10`, `symless/synergy-core:debian10`, `symless/synergy-core:fedora30`, `symless/synergy-core:fedora29`, and `symless/synergy-core:centos8` also have openssl development libraries installed on them as well.

There is a problem with not all of them having the static libraries installed, so I changed cmake to only statically compile OpenSSL on windows.

I still don't know why the windows test doesn't run.

I wrote a script that runs the same as the runner, and it works no problem.

```powershell
$env:QT_BASE_DIR="C:\Users\kyle\Documents\GitHub\synergy-core\deps\Qt"
$env:BONJOUR_BASE_DIR="C:\Users\kyle\Documents\GitHub\synergy-core\deps\bonjour"
$env:QT_VERSION="5.12.6"
$env:QT_BASE_URL="http://qt.mirror.constant.com/"
$env:BONJOUR_SDK_HOME="C:\Users\kyle\Documents\GitHub\synergy-core\deps\bonjour\BonjourSDK"
$env:CMAKE_PREFIX_PATH="C:\Users\kyle\Documents\GitHub\synergy-core\deps\Qt\5.12.6\msvc2017_64\"

aqt install --outputdir $env:QT_BASE_DIR --base $env:QT_BASE_URL $env:QT_VERSION windows desktop win64_msvc2017_64
New-Item -Force -ItemType Directory -Path $env:BONJOUR_BASE_DIR
$client = new-object System.Net.WebClient
$client.DownloadFile("https://binaries.symless.com/bonjour/BonjourSDK.zip",".\bonjoursdk.zip")
[System.IO.Compression.ZipFile]::ExtractToDirectory(".\bonjoursdk.zip", $env:BONJOUR_BASE_DIR)

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
. ./version
msbuild synergy-core.sln /p:Configuration=Release

.\bin\Release\unittests.exe
```

**Comment by aquacash5** [comment]
I did change the changelog, but the action fails.

**Comment by aquacash5** [comment]
Waiting on #6915 to fix windows test.

**Pull request merged**
