### PR TITLE
Re-implement packaging for GitHub workflows (Linux)

### PR DESCRIPTION
**Pull request by nbolton**
https://symless.atlassian.net/browse/S1-1693
https://symless.atlassian.net/browse/S1-1694

To test on Ubuntu and Fedora:
1. `./scripts/install_deps.py`
2. `cmake -B build --preset=linux-release`
3. `cmake --build build -j8`
4. `./scripts/package.py`

### CODE REVIEW

**Comment by aquacash5** [comment]
I don't think you should have to run `install_deps.py` to run `package.py`. I suggest adding a cli option that would create the venv if included. (ex `./scripts/package.py --make-venv`)

**Review by aquacash5 — CHANGES_REQUESTED** [review]
Fedora doesn't produce a package after running `scripts/package.py`

**Review by aquacash5 — APPROVED** [review]
Nevermind there was some other issue on my vm

**Comment by nbolton** [comment]
> I don't think you should have to run `install_deps.py` to run `package.py`. I suggest adding a cli option that would create the venv if included. (ex `./scripts/package.py --make-venv`)

I did consider this, but then realised that it's an edge case, so adding complexity seemed wasteful.

**Pull request merged**
