### PR TITLE
Use CMAKE_DL_LIBS instead of dl for BSD

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by yupi2** [comment]
Were there any compatibility issues you experienced where `dl` was not the library?

**Comment by yurivict** [comment]
Yes, BSDs don't have libdl, this is why cmake has this macro.

**Comment by yurivict** [comment]
@nbolton Could you please merge this trivial patch?

**Comment by nbolton** [comment]
@yurivict Ok! #6373

**Comment by nbolton** [comment]
Fixes #6492

**Pull request merged**
